// Curated word list for typing tests — real words chosen for diverse finger pattern coverage.
// Mix of lengths (3–7 chars) and hand distributions.

const WORDS: string[] = [
  // 3-letter
  "the","and","for","are","but","not","you","all","can","was","one","our",
  "out","who","get","has","him","his","how","man","new","now","old","see",
  "two","way","did","end","far","few","got","let","put","say","she","too",
  "use","her","its","may","set","try","why","ask","cut","day","dog","eat",
  "eye","fly","fun","hit","hot","job","key","kid","law","lay","leg","low",
  "map","mix","pay","run","sit","six","sky","ten","top","war","win","yes",
  "add","age","ago","aim","air","bad","bag","ban","bar","bay","bed","big",
  "bit","box","boy","bus","buy","car","cup","dry","due","ear","era","err",
  "fat","fit","fix","gap","gas","god","gun","gut","gym","hat","hay","hub",
  "ice","ill","inn","ion","jar","jaw","jet","joy","lab","lap","led","lip",
  "log","lot","mad","mud","nod","nor","odd","oil","own","pan","pat","pen",
  "pet","pie","pig","pit","pod","pop","pot","pub","raw","ray","red","rid",
  "rip","rod","row","rub","rug","rum","sad","sap","saw","sea","sin","sir",
  "sob","sod","son","sow","spa","spy","sum","sun","tab","tan","tap","tar",
  "tax","tip","toe","ton","toy","tug","tux","van","vat","via","web","wet",
  "win","wit","woe","won","woo","wow","yam","zip","zoo",

  // 4-letter
  "that","with","this","have","from","they","will","been","said","each",
  "into","then","more","also","what","when","them","some","come","back",
  "give","good","hand","here","high","just","keep","kind","know","last",
  "left","life","like","long","look","made","make","many","much","must",
  "name","need","next","only","open","over","part","play","read","same",
  "send","show","such","take","than","time","used","very","want","well",
  "were","word","work","year","your","able","both","call","city","does",
  "down","even","face","feel","find","fire","free","full","game","girl",
  "head","help","home","idea","land","lead","line","live","love","mind",
  "move","near","once","plan","real","rest","road","room","rule","seem",
  "self","side","size","skin","song","soon","sort","star","stay","step",
  "stop","talk","tell","test","text","till","town","tree","true","turn",
  "type","unit","upon","view","vote","walk","wall","warm","wear","week",
  "west","wide","wife","wild","wind","wise","wish","yard","zero","area",
  "atom","aunt","axis","baby","bail","bait","bake","ball","band","bang",
  "bank","barn","base","bath","bead","beak","beam","bear","beat","beef",
  "bell","belt","bend","best","bind","bird","bite","blow","blue","body",
  "bold","bolt","bond","bone","boom","boot","born","boss","bowl","brow",
  "buck","bulk","bull","burn","burp","buzz","cafe","cage","cake","calm",
  "camp","cape","card","care","cart","case","cast","cave","cell","chat",
  "chip","chop","clap","clay","clue","coal","coat","code","coil","coin",
  "cold","cone","cook","cool","cord","core","corn","cost","coup","crew",
  "crop","crow","curl","dart","data","date","deal","dean","debt","deck",
  "deed","deep","deer","deny","desk","dine","dish","disk","dive","dock",
  "dome","door","dose","dram","draw","drew","drip","drop","drug","drum",
  "duck","duel","dumb","dump","dung","dusk","dust","duty","dye","each",
  "earn","ease","edge","envy","epic","ever","evil","exam","exit","fade",
  "fail","fair","fake","fall","fame","farm","fast","fate","feat","feed",
  "feet","felt","fend","fest","fern","firm","fish","fist","flag","flat",
  "flaw","fled","flew","flex","flip","flow","foam","fold","folk","fond",
  "food","fool","foot","fork","form","fort","foul","four","fowl","fuel",
  "fund","fuse","fuzz","gale","gaze","gear","germ","gist","glad","glow",
  "glue","gnaw","goal","goat","gold","gone","gore","gown","grab","gram",
  "gray","grew","grin","grip","grit","grow","gulf","guru","gust","half",
  "hale","hall","halt","hang","hard","hare","harm","harp","haste","hate",
  "haul","heal","heap","heat","heel","held","helm","hemp","hero","hike",
  "hill","hint","hire","hive","hold","hole","holy","hone","hood","hook",
  "hoop","hope","horn","host","huge","hull","hump","hunt","hurl","hurt",
  "hush","icon","inch","iron","itch","jail","jest","join","jump","junk",
  "just","keen","kept","kick","kill","kind","king","kiss","knit","knot",
  "lace","lack","lake","lame","lamp","lane","lard","lark","lash","last",
  "late","laud","lawn","lazy","leak","lean","leap","lend","lens","lick",
  "limp","link","lint","lion","list","load","loan","lock","loft","lone",
  "loot","lord","lore","lose","loss","loud","lure","lurk","lush","lust",
  "mall","mane","mare","mark","mask","mast","mate","maze","meal","mean",
  "meat","melt","memo","menu","mesh","mess","mild","mill","mine","mint",
  "miss","mist","moan","mock","mode","mold","mole","monk","moon","moor",
  "more","moss","most","moth","mull","myth","nail","nap","neck","nerd",
  "nest","news","node","none","noon","norm","nose","note","noun","nude",
  "oat","oath","obey","omen","oral","orb","orca","oven","pace","pack",
  "pact","page","pain","pair","palm","park","pass","past","path","pave",
  "peak","peel","peer","perk","pest","pick","pike","pile","pill","pine",
  "pipe","pity","plod","plot","plow","plug","plum","plus","poem","poet",
  "poll","pond","pool","port","pose","post","pour","prey","prod","prop",
  "pull","pump","pure","push","rack","rage","raid","rail","rain","rake",
  "ramp","rang","rank","rant","rash","rate","read","reef","reel","reek",
  "rely","rend","rent","rich","ride","rift","rime","ring","riot","rise",
  "risk","rite","roam","roar","robe","rock","role","romp","roof","root",
  "rope","rose","ruse","rush","rust","sake","sale","salt","same","sand",
  "sane","sang","sank","sash","save","scan","scar","seal","seam","seek",
  "seep","self","sell","shed","shin","ship","shoe","shot","shun","shut",
  "sigh","silk","sill","silo","sing","slab","slap","slay","slid","slim",
  "slip","slot","slow","slum","snap","snag","soak","soar","sock","sofa",
  "soil","sole","some","sore","soul","soup","span","spar","spin","spit",
  "spot","spun","stab","stem","stew","stir","stub","stun","such","suit",
  "sulk","sung","sunk","surf","surge","swap","swat","sway","sweat","swim",
  "swum","tale","tall","tame","tang","taut","tear","tend","tent","test",
  "text","tide","tied","tier","tile","till","time","tiny","tire","toll",
  "tore","torn","toss","tote","tour","town","trap","trim","trip","trod",
  "trot","tuft","tuna","turf","tusk","tutu","twin","ugly","upon","urge",
  "vain","vale","vane","vary","vast","veil","vein","vent","vest","veto",
  "vibe","vile","vine","vise","void","wand","ward","warp","wart","wary",
  "wend","whim","whip","whit","whiz","whom","wick","wilt","wink","wire",
  "wiry","woke","womb","worm","worn","writ","yell","yore","zeal","zest",
  "zinc","zone",

  // 5-letter
  "about","after","again","along","among","began","black","blood","board",
  "bring","built","child","clean","clear","close","comes","could","cover",
  "court","cross","dream","drink","drive","early","every","event","extra",
  "field","final","first","floor","focus","force","found","front","glass",
  "going","grace","grand","grass","great","green","group","guess","guide",
  "happy","heart","heavy","hence","horse","hours","human","image","index",
  "inner","large","later","learn","least","legal","level","light","local",
  "lower","major","means","media","might","model","money","month","music",
  "night","north","offer","often","order","other","paper","party","peace",
  "phase","phone","photo","place","plain","plant","plate","point","power",
  "press","price","print","prize","prove","pulse","quite","raise","range",
  "rapid","reach","ready","right","river","round","royal","rural","scale",
  "scene","score","sense","seven","shall","shape","share","sharp","shift",
  "short","sight","since","skill","sleep","slide","small","smart","smile",
  "smoke","solid","solve","sound","south","space","spend","split","staff",
  "stage","stand","start","state","steel","still","stone","store","storm",
  "story","study","style","sweet","table","teach","think","three","throw",
  "title","today","total","touch","track","trade","trail","train","tried",
  "trust","truth","under","until","upper","value","verse","voice","watch",
  "water","whole","world","worry","worth","would","write","wrong","young",
  "adult","alert","alike","align","arise","armor","array","aside","atlas",
  "attic","audit","avoid","awful","baker","basic","basis","batch","began",
  "being","blade","blank","blast","blaze","bleed","bless","blind","bliss",
  "bloat","bloom","blown","blown","blunt","blurb","blurt","boost","boxer",
  "brace","brand","brave","bread","break","breed","bribe","brick","bride",
  "brief","brine","brisk","broad","broke","brook","broth","brown","bruise",
  "brush","brute","budge","bulge","bunch","burst","buyer","cabin","cache",
  "camel","carry","catch","cause","chair","chalk","chant","chart","chase",
  "cheap","check","cheer","chess","chest","chief","chili","chunk","civil",
  "claim","clash","class","click","climb","clock","clone","cloth","cloud",
  "clown","coast","color","comet","comic","comma","coral","count","craft",
  "crank","crash","craze","creek","creep","crest","crime","crisp","croak",
  "crook","crowd","cruel","crush","crust","curve","cycle","daily","dance",
  "dated","debut","decay","decor","decoy","delay","depth","devil","digit",
  "dirty","disco","ditch","dizzy","dodge","doing","doubt","dough","dowel",
  "draft","drain","drawn","dread","drill","droop","drove","drown","dumpy",
  "dwarf","eager","earth","eight","elect","elite","email","empty","enjoy",
  "enter","equal","error","essay","excel","exist","faint","faith","false",
  "fancy","fatal","favor","feast","fewer","fiber","fight","fixed","flame",
  "flank","flare","flash","fleet","flesh","flung","flute","forte","forum",
  "fraud","fresh","front","froze","fruit","fryer","fully","funny","gauge",
  "ghost","given","giver","glare","glaze","gleam","gloom","glory","glove",
  "going","grain","grasp","grave","graze","greed","greet","grief","grind",
  "groan","grope","gross","grove","growl","gruel","grunt","guard","guest",
  "guise","gulch","guppy","habit","handy","harsh","haven","heady","hired",
  "hoist","honor","honor","hover","humor","hurry","ideal","idiom","idiot",
  "imply","infer","inlet","inlet","input","inter","irony","issue","ivory",
  "joker","jumpy","kneel","knife","knock","known","label","lance","latch",
  "laugh","layer","lemon","liner","logic","loose","loser","lover","lucky",
  "lunar","lyric","magic","maple","march","match","mayor","mercy","merit",
  "metal","minor","minus","mirth","mixed","mourn","mouth","muddy","murky",
  "naive","nasty","naval","nerve","never","noble","noisy","notch","novel",
  "nurse","nymph","occur","ocean","olive","onward","optic","orbit","outdo",
  "overt","oxide","ozone","panic","pasta","pause","payoff","pearl","pesky",
  "petal","petty","piano","pixel","pizza","place","plaid","plaza","plead",
  "pleat","pluck","plumb","plunge","plush","poach","polar","polka","pouch",
  "pouch","prank","price","pride","prime","prior","probe","prone","prong",
  "proto","prune","psalm","pupil","purse","queen","query","quota","rabbi",
  "radar","rainy","rally","ranch","rebel","refer","reign","relax","repay",
  "retry","rider","ridge","rifle","rigid","risen","risky","rival","robin",
  "rocky","roman","rouge","rough","rouse","route","ruler","rusty","sadly",
  "saint","salad","sandy","sassy","sauce","savor","savvy","scald","scalp",
  "scant","scary","scoop","scope","scorn","scout","screw","seize","serve",
  "setup","shaft","shaky","shame","shelf","shell","shirt","shock","shone",
  "shook","shoot","shore","shown","showy","shrug","siege","silky","silly",
  "simmer","sinew","sixth","sixty","siren","slant","slash","slave","sleek",
  "sleet","slew","slice","slick","sling","slink","slop","sloth","slump",
  "slurp","smash","smell","smirk","snare","sneak","sniff","snore","snort",
  "snowy","snuck","solar","sooty","sorry","spare","spark","spawn","spear",
  "speck","speed","spill","spire","spite","spoof","spoon","spray","spree",
  "squad","squat","squid","stack","stain","stake","stale","stall","stamp",
  "stark","starve","stave","stead","steam","steep","steer","stern","stiff",
  "sting","stock","stomp","stoop","strap","straw","stray","strip","strut",
  "stuck","studs","stump","suede","sugar","sunny","super","surge","swamp",
  "swear","swipe","swirl","swoop","tangy","taunt","taxed","tepid","theft",
  "theme","there","thick","thief","thing","thorn","tidal","tiger","tinge",
  "tipsy","tired","toasty","toxic","toyed","tramp","trash","trawl","tread",
  "trend","triad","trick","tried","trill","tripe","trite","tromp","troop",
  "trout","truck","truer","trump","truss","tuber","tulip","tumor","tuner",
  "tunic","twang","tweak","tweed","twice","twirl","twitch","ultra","unify",
  "union","unity","unset","upset","usher","utter","vague","valid","vapor",
  "vault","vigor","viral","virus","visit","vital","vivid","vocal","vodka",
  "vouch","waist","waltz","waste","wedge","weigh","weird","whack","whale",
  "wheat","wheel","where","which","while","whirl","whose","wield","witty",
  "xenon","yacht","yearn","yield","zippy",
];

let _pool: string[] = [];

function _refill() {
  // Shuffle a fresh copy of the word list into the pool
  const copy = [...WORDS];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  _pool = copy;
}

/** Generate a passage of approximately `n` words, shuffled for diverse bigram coverage. */
export function generatePassage(n: number): string {
  const result: string[] = [];
  while (result.length < n) {
    if (_pool.length < 50) _refill();
    result.push(_pool.pop()!);
  }
  return result.join(' ');
}
